services:
  gateway:
    build: ./gateway
    ports:
      - "80:80"
    networks:
      - bridge_network
    depends_on:
      - service_a

  service_a:
    build: ./service_a
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge
